### ISSUE TITLE
[Bug]: Better appstream summary

### ISSUE THREAD

**Issue by bertob** [fabrialberio/PinApp#44] opened 2024-01-14 23:49 UTC
The current appstream summary `Create and edit application shortcuts` is good, but slightly longer than the recommended maximum (35 chars). A simple fix could be using "app" rather than "application" here, i.e. `Create and edit app shortcuts`.

**Comment by fabrialberio** [comment] 2024-02-06 10:00
Duplicate of #39, it will be fixed in the next update.

**Closed by fabrialberio** 2024-02-06 10:00 UTC
Labels: bug
